version: '3.9'

services:
  server:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty312
      POSTGRES_DB: levchdb

  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


