name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: levchdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwerty312
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker images
      run: |
        docker build -t myapp-server:latest .
        docker build -t myapp-db:latest ./db

    - name: Push Docker images to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag myapp-server:latest ghcr.io/${{ github.repository_owner }}/myapp-server:latest
        docker tag myapp-db:latest ghcr.io/${{ github.repository_owner }}/myapp-db:latest
        docker push ghcr.io/${{ github.repository_owner }}/myapp-server:latest
        docker push ghcr.io/${{ github.repository_owner }}/myapp-db:latest

    - name: Deploy to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker tag myapp-server:latest ${{ secrets.DOCKER_HUB_USERNAME }}/myapp-server:latest
        docker tag myapp-db:latest ${{ secrets.DOCKER_HUB_USERNAME }}/myapp-db:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp-server:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp-db:latest